# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ExtendedUser',
        ),
    ]
