# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20170805_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='civic_name',
        ),
    ]
