# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-05 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_extendeduser_civic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='avatar',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='background',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
