# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0004_auto_20170805_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('logo', models.ImageField(upload_to='teams/avatars')),
                ('background', models.ImageField(upload_to='teams/backgrounds')),
                ('teamleaders', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='avatar',
            field=models.ImageField(upload_to='users/avatars'),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='background',
            field=models.ImageField(upload_to='users/backgrounds'),
        ),
    ]
