# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20170807_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='teamleaders',
        ),
    ]
