# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_remove_team_teamleaders'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='requirements',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
