# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_team_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='requirements',
            field=models.TextField(blank=True),
        ),
    ]
