# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20170809_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='people_needed',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
