# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0011_extendeduser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamleaders',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
