# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_team_teamleaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Team'),
        ),
    ]
