# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-16 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20170812_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriversLicenceCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='drivers_licence',
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='staff.Team'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='drivers_licence',
            field=models.ManyToManyField(to='staff.DriversLicenceCategories'),
        ),
    ]
