# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 14:04
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0018_auto_20170816_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('body', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('on_time', models.NullBooleanField()),
                ('comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TShirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='child_record',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='emergency_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+4570131415'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='special_considerations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='sock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Sock'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='tshirt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.TShirt'),
        ),
    ]
