# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_auto_20170924_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unauthenticated_session',
            new_name='UnauthenticatedSession',
        ),
        migrations.RemoveField(
            model_name='extendedgroup',
            name='group',
        ),
        migrations.DeleteModel(
            name='ExtendedGroup',
        ),
    ]
