# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_auto_20170925_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='postal_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
