# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_auto_20170927_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='city',
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='postal_code',
            field=models.CharField(max_length=10),
        ),
    ]
