# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0030_auto_20170929_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Team'),
        ),
    ]
