# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0031_auto_20170929_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='requirements',
            new_name='description',
        ),
    ]
