# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0032_auto_20170930_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='accepts_applications',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
