# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0033_team_accepts_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthenticatedsession',
            name='otp',
            field=models.CharField(max_length=4),
        ),
    ]
